version: '3.4'

services:
  api:
    image: nome-do-seu-projeto-api
    build:
      context: .
      dockerfile: SeuProjeto.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
